title: "Democratizing AI Inclusivity: A Red-Teaming Repository of Existing Social Bias"
theme: minima

navigation:
  - title: Home
    url: /
  - title: Background
    url: /background
  - title: Dataset Collection Methods
    url: /dataset_collection_methods

    
