title: "Democratizing AI Inclusivity"
subtitle: "A Red-Teaming Repository of Existing Social Bias Prompts"
theme: minima

navigation:
  - title: Home
    url: /
  - title: Background
    url: /background
  - title: Dataset Collection Methods
    url: /dataset_collection_methods

    
