theme: minima

author:
  name: Simone Van Taylor
  email: svannie678@gmail.com


navigation:
  - title: Home
    url: /
  - title: Background
    url: /background
  - title: Dataset Collection Methods
    url: /dataset_collection_methods

    
