title: "Democratizing AI Inclusivity: A Red-Teaming Dataset of Existing Bias Prompts"
theme: minima

navigation:
  - title: Home
    url: /
  - title: Background
    url: /background
  - title: Dataset Collection Methods
    url: /dataset_collection_methods

    
